version: '3.4'

services:

  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:5002 --access-logfile - --reload "landing_page.app:create_app()"
    restart: always
    env_file:
      - '.env'
    volumes:
      - '.:/landing_page'
    ports:
      - '5002:5002'

  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass Bloverse2021
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  celery_lpage:
    build: .
    command: celery -A landing_page.tasks.lpage.celery worker -B -l info -E -Q lpage
    env_file:
      - '.env'
    volumes:
      - '.:/landing_page'


  # proxy:
  #   build: proxy
  #   restart: always
  #   ports:
  #     - "81:81"


   
volumes:
  redis:


